// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kyamalabs/users/internal/worker (interfaces: TaskDistributor)
//
// Generated by this command:
//
//	mockgen -package mockwk -destination=internal/worker/mock/distributor.go github.com/kyamalabs/users/internal/worker TaskDistributor
//

// Package mockwk is a generated GoMock package.
package mockwk

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	worker "github.com/kyamalabs/users/internal/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskCacheEnsName mocks base method.
func (m *MockTaskDistributor) DistributeTaskCacheEnsName(arg0 context.Context, arg1 *worker.PayloadCacheEnsName, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskCacheEnsName", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskCacheEnsName indicates an expected call of DistributeTaskCacheEnsName.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskCacheEnsName(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskCacheEnsName", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskCacheEnsName), varargs...)
}
