// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	DeleteProfile(ctx context.Context, walletAddress string) error
	GetProfile(ctx context.Context, walletAddress string) (Profile, error)
	GetProfilesCount(ctx context.Context) (int64, error)
	GetReferer(ctx context.Context, referee string) (Referral, error)
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error)
	ListReferrals(ctx context.Context, arg ListReferralsParams) ([]Referral, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
