// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: rpc_list_referrals.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReferralsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddress string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Page          int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListReferralsRequest) Reset() {
	*x = ListReferralsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_referrals_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferralsRequest) ProtoMessage() {}

func (x *ListReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_referrals_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferralsRequest.ProtoReflect.Descriptor instead.
func (*ListReferralsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_referrals_proto_rawDescGZIP(), []int{0}
}

func (x *ListReferralsRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *ListReferralsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReferralsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReferralsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page           int32       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32       `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalReferrals int32       `protobuf:"varint,3,opt,name=total_referrals,json=totalReferrals,proto3" json:"total_referrals,omitempty"`
	Referrals      []*Referral `protobuf:"bytes,4,rep,name=referrals,proto3" json:"referrals,omitempty"`
}

func (x *ListReferralsResponse) Reset() {
	*x = ListReferralsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_referrals_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReferralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferralsResponse) ProtoMessage() {}

func (x *ListReferralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_referrals_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferralsResponse.ProtoReflect.Descriptor instead.
func (*ListReferralsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_referrals_proto_rawDescGZIP(), []int{1}
}

func (x *ListReferralsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReferralsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReferralsResponse) GetTotalReferrals() int32 {
	if x != nil {
		return x.TotalReferrals
	}
	return 0
}

func (x *ListReferralsResponse) GetReferrals() []*Referral {
	if x != nil {
		return x.Referrals
	}
	return nil
}

var File_rpc_list_referrals_proto protoreflect.FileDescriptor

var file_rpc_list_referrals_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0e,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e,
	0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x9d,
	0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61,
	0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x61, 0x6c, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x61, 0x6c, 0x73, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x79, 0x61,
	0x6d, 0x61, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_list_referrals_proto_rawDescOnce sync.Once
	file_rpc_list_referrals_proto_rawDescData = file_rpc_list_referrals_proto_rawDesc
)

func file_rpc_list_referrals_proto_rawDescGZIP() []byte {
	file_rpc_list_referrals_proto_rawDescOnce.Do(func() {
		file_rpc_list_referrals_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_list_referrals_proto_rawDescData)
	})
	return file_rpc_list_referrals_proto_rawDescData
}

var file_rpc_list_referrals_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_referrals_proto_goTypes = []interface{}{
	(*ListReferralsRequest)(nil),  // 0: pb.ListReferralsRequest
	(*ListReferralsResponse)(nil), // 1: pb.ListReferralsResponse
	(*Referral)(nil),              // 2: pb.Referral
}
var file_rpc_list_referrals_proto_depIdxs = []int32{
	2, // 0: pb.ListReferralsResponse.referrals:type_name -> pb.Referral
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_referrals_proto_init() }
func file_rpc_list_referrals_proto_init() {
	if File_rpc_list_referrals_proto != nil {
		return
	}
	file_referral_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_list_referrals_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReferralsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_list_referrals_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReferralsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_list_referrals_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_referrals_proto_goTypes,
		DependencyIndexes: file_rpc_list_referrals_proto_depIdxs,
		MessageInfos:      file_rpc_list_referrals_proto_msgTypes,
	}.Build()
	File_rpc_list_referrals_proto = out.File
	file_rpc_list_referrals_proto_rawDesc = nil
	file_rpc_list_referrals_proto_goTypes = nil
	file_rpc_list_referrals_proto_depIdxs = nil
}
