Project users_service {
  database_type: 'PostgreSQL'
  Note: '''
    # Users Service Database
  '''
}

Table profiles {
  wallet_address varchar [pk]
  gamer_tag varchar [unique, not null]
  created_at timestamptz [not null, default: `now()`]
}

Table referrals {
  id UUID [pk, default: `gen_random_uuid()`]
  referrer varchar [ref: > profiles.wallet_address]
  referee varchar [ref: - profiles.wallet_address]
  referred_at timestamptz [not null, default: `now()`]
}
